create or replace editionable trigger xxventuri.xxeba_sales_customers_h_aiu after
    insert or update on xxventuri.eba_sales_customers
    for each row
begin
    insert into xxeba_sales_customers_hist (
        id,
        row_version_number,
        row_key,
        customer_name,
        tags,
        default_rep_id,
        customer_sic,
        customer_duns,
        customer_web_site,
        customer_stock_symb,
        customer_number_of_emp,
        customer_is_public_comp_yn,
        customer_facebook,
        customer_linkedin,
        customer_twitter,
        customer_description,
        customer_territory_id,
        customer_is_key_account_yn,
        created_by,
        created,
        updated_by,
        updated,
        account_source,
        gst_no,
        industry_id,
        classification_id,
        pan_number,
        phone_number,
        mobile_number,
        email_address,
        customer_code,
        last_updated_latitude,
        last_updated_longitude,
        status,
        verified_on,
        verified_by,
        verify_comments,
        team_lead_comments,
        team_lead_id
    ) values ( :new.id,
               :new.row_version_number,
               :new.row_key,
               :new.customer_name,
               :new.tags,
               :new.default_rep_id,
               :new.customer_sic,
               :new.customer_duns,
               :new.customer_web_site,
               :new.customer_stock_symb,
               :new.customer_number_of_emp,
               :new.customer_is_public_comp_yn,
               :new.customer_facebook,
               :new.customer_linkedin,
               :new.customer_twitter,
               :new.customer_description,
               :new.customer_territory_id,
               :new.customer_is_key_account_yn,
               :new.created_by,
               :new.created,
               :new.updated_by,
               :new.updated,
               :new.account_source,
               :new.gst_no,
               :new.industry_id,
               :new.classification_id,
               :new.pan_number,
               :new.phone_number,
               :new.mobile_number,
               :new.email_address,
               :new.customer_code,
               :new.last_updated_latitude,
               :new.last_updated_longitude,
               :new.status,
               :new.verified_on,
               :new.verified_by,
               :new.verify_comments,
               :new.team_lead_comments,
               :new.team_lead_id );

end;
/

alter trigger xxventuri.xxeba_sales_customers_h_aiu enable;


-- sqlcl_snapshot {"hash":"510c4cf8b935151598597e85f63928359bb7813a","type":"TRIGGER","name":"XXEBA_SALES_CUSTOMERS_H_AIU","schemaName":"XXVENTURI","sxml":""}